### PR TITLE
Ruler scale factor

### PR DESCRIPTION
**Pull request by FedeClaudi**
Hi Marco, 

I've made a small edit to `Ruler` to add a `scale_factor`. I needed this because in `brainrender` meshes are defined in units of micrometers but I wanted to display distance in `mm`, so I had to scale the distance number computed by `Ruler` accordingly. 

Let me know if you'd like to implement this in `vedo` and if/when you could release a version with it, I'm working on a few additions [to brainrender](https://github.com/BrancoLab/brainrender/issues/104) and would like to have this edited version of `Ruler` in it.

### CODE REVIEW

**Comment by marcomusy** [comment]
Oh actually it's a good idea, I would prefer calling it `unitScale=1` rather than `scaling_factor` as vedo uses camelCase convention.
I would also force the user to specify the string `units`, and not leaving it blank, if unitScale!=1

**Comment by FedeClaudi** [comment]
okay, of course that sounds good :) 
Do you want me to add this to the PR or will you do it?

**Comment by marcomusy** [comment]
feel free to add it! thanks!

**Comment by FedeClaudi** [comment]
done, have a look :)

**Review by marcomusy — APPROVED** [review]

**Pull request merged**
